services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  postgres_gateway:
    image: postgres:15
    environment:
      POSTGRES_DB: gatewaydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  postgres_storage:
    image: postgres:15
    environment:
      POSTGRES_DB: storagedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  postgres_bank:
    image: postgres:15
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


  bank-service:
    build:
      context: ./bank-service
    depends_on:
      - kafka
      - postgres_bank
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_bank:5432/bankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"

  gateway:
    build:
      context: ./gateway
    depends_on:
      - kafka
      - postgres_gateway
    environment:
      WEBCLIENT_BASE_URL: http://bank-service:8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_gateway:5432/gatewaydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"

  storage:
    build:
      context: ./storage
    depends_on:
      - kafka
      - postgres_storage
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_storage:5432/storagedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8082"